# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smd_rcpp <- function(x, treat, weights, targets) {
    .Call(`_OutcomeWeights_smd_rcpp`, x, treat, weights, targets)
}

summary_smd_rcpp <- function(cbr) {
    .Call(`_OutcomeWeights_summary_smd_rcpp`, cbr)
}

summary_weights_rcpp <- function(weights) {
    .Call(`_OutcomeWeights_summary_weights_rcpp`, weights)
}

scaled_Ztildex_maker <- function(alpha, res_z, res_d) {
    .Call(`_OutcomeWeights_scaled_Ztildex_maker`, alpha, res_z, res_d)
}

